30.04.2021
runcell(0, 'C:/Users/B150M-C/.spyder-py3/temp.py')
C:\Users\B150M-C\.spyder-py3\temp.py:31: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self.A = np.array([X,A])
Traceback (most recent call last):

  File "C:\Users\B150M-C\.spyder-py3\temp.py", line 52, in <module>
    Wl1.Qf(X, A1)

  File "C:\Users\B150M-C\.spyder-py3\temp.py", line 32, in Qf
    self.A = [self.A[:,i] for i,x in enumerate(X)]

  File "C:\Users\B150M-C\.spyder-py3\temp.py", line 32, in <listcomp>
    self.A = [self.A[:,i] for i,x in enumerate(X)]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed